apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./argocd-monorepo-controller
- ./argocd-monorepo-repo-server
images:
- name: quay.io/argoprojlabs/argocd-monorepo-controller
  newName: quay.io/argoproj-labs/argocd-monorepo-controller
  newTag: latest
