dir: '{{.InterfaceDir}}/mocks'
structname: '{{.InterfaceName}}'
filename: '{{.InterfaceName}}.go'
pkgname: mocks

template-data:
  unroll-variadic: true

packages:
  github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned/typed/application/v1alpha1:
    interfaces:
      AppProjectInterface: {}
      ArgoprojV1alpha1Interface: {}
      ApplicationInterface: {}
  github.com/argoproj/argo-cd/v3/pkg/client/listers/application/v1alpha1:
    interfaces:
      ApplicationLister: {}
  github.com/argoproj/argo-cd/v3/pkg/client/clientset/versioned:
    interfaces:
      Interface: {}
  github.com/argoproj/argo-cd/v3/reposerver/apiclient:
    interfaces:
      RepoServerServiceClient: {}
  github.com/argoproj/argo-cd/v3/util/db:
    interfaces:
      ArgoDB: {}
  github.com/argoproj/argo-cd/v3/util/git:
    interfaces:
      Client: {}
  github.com/argoproj/argo-cd/v3/util/helm:
    interfaces:
      Client: {}
  github.com/argoproj/argo-cd/v3/util/oci:
    interfaces:
      Client: {}
  github.com/argoproj/argo-cd/v3/util/io:
    interfaces:
      TempPaths: {}
  github.com/argoproj/argo-cd/v3/util/workloadidentity:
    interfaces:
      TokenProvider: {}
