- description: Application changed
  oncePer: app.metadata.annotations["mrp-controller.argoproj.io/change-revision"]
  send:
  - app-application-changed
  when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']

