apiVersion: v1
data:
  service.email.mailhog: |
    host: mailhog-service.mailhog.svc.cluster.local
    port: 1025
    from: argocd@argoproj.io
    html: false
    insecure_skip_verify: true
#    username: "mail"
#    password: "***"
  template.app-application-changed: |
    email:
      subject: Application {{.app.metadata.name}} has been changed
    message: |
      Application {{.app.metadata.name}} has been changed at {{.app.status.operationState.finishedAt}}.
      Git revision is {{index .app.metadata.annotations "mrp-controller.argoproj.io/change-revision"}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  trigger.on-application-changed: |
    - description: Application changed
      oncePer: app.metadata.annotations["mrp-controller.argoproj.io/change-revision"]
      send:
      - app-application-changed
      when: app.status.operationState != nil and app.status.operationState.phase in ['Succeeded']
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argocd-notifications-cm
